# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Action Test

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          echo "variable from shell environment : $env_var"
        env:
          REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
          ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
          OVERRIDE_VAR: ${{ vars.OVERRIDE_VAR }}
          
        - name: ${{ vars.HELLO_WORLD_STEP }}
          if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
          uses: actions/hello-world-javascript-action@main
          with:
            who-to-greet: ${{ vars.GREET_NAME }}

      - name: Setting .env
        run: |
         cat ${{ github.repository }}
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}" >> .env
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "GITHUB_REPOSITORY=${{ secrets.GITHUB_REPOSITORY }}" >> .env
          cat .env
          cat .env | grep GITHUB_REPOSITORY | wc -m
          swimingkim/blog