# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Setting .env
        run: |
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}" >> .env
          echo "ANALYZE=${{ secrets.ANALYZE }}" >> .env
          echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" >> .env
          echo "NOTION_DATABSE_ID=${{ secrets.NOTION_DATABSE_ID }}" >> .env
          echo "NOTION_HOMEPAGE_ID=${{ secrets.NOTION_HOMEPAGE_ID }}" >> .env
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
          echo "GIT_USER=${{ secrets.GIT_USER }}" >> .env
          echo "REPO_NAME=${{ secrets.REPO_NAME }}" >> .env
          echo "WORKFLOW_ID=${{ secrets.WORKFLOW_ID }}" >> .env
          cat .env

      - name: Installing my packages
        run: npm install --legacy-peer-deps 

      - name: Build my App
        run: npm run gh_build && npm run gh_action_deploy

      - name: Deploy 🚀
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message